### PR TITLE
Update iOS headers for RN 0.40.0

### PR DESCRIPTION
**Pull request by ryancoughlin**

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
Can you update the example project to use RN 0.40+?

**Comment by ryancoughlin** [comment]
Blake, updated the example project. When I open the ActivityView I get this error

simulator screen shot mar 22 2017 12 02 01 pm
```
  _clickHandler() {
    ActivityView.show({
      text: 'ActivityView for React Native',
      url: 'https://github.com/naoufal/react-native-activity-view',
      imageUrl: 'http://facebook.github.io/react/img/logo_og.png'
    });
  }
```

If I remove `imageUrl: 'http://facebook.github.io/react/img/logo_og.png'` it works great. Not sure if this was happening before or not.

**Comment by BlakeWilliams** [comment]
Does it work if you copy https://github.com/naoufal/react-native-activity-view/blob/c3df178c0c5b5479d4c37b8f5c7b50f4a4b356a0/ActivityView.m ?

**Comment by ryancoughlin** [comment]
The only thing changed in that file should have been the headers

**Comment by ryancoughlin** [comment]
@BlakeWilliams Updated and all good.

**Comment by ryancoughlin** [comment]
🎉 🚢 🐧

**Comment by ryancoughlin** [comment]
@naoufal Is it possible to add a new release for these changes?

**Comment by naoufal** [comment]
@ryancoughlin 🚀 shipped to npm under `0.2.11`!

**Comment by ryancoughlin** [comment]
🎉🚀🚢

**Pull request merged**
