### PR TITLE
execute on main thread to avoid crash on ios 9

### PR DESCRIPTION
**Pull request by chirag04**
cc @naoufal 

fixes https://github.com/naoufal/react-native-activity-view/issues/15

### CODE REVIEW

**Comment by naoufal** [comment]
Thanks @chirag04. 👍

**Comment by chirag04** [comment]
That was quick. thanks :+1:

**Comment by chirag04** [comment]
I will submit a patch that landed in react native itself for crash on ios. Let's publish on npm after that?

**Comment by naoufal** [comment]
@chirag04 Sounds good.  I can review and publish tonight if you can get it in before then.

**Pull request merged**
