### PR TITLE
RN 0.32.0 - loadImageWithTag is now loadImageWithURLRequest

### PR DESCRIPTION
**Pull request by JBerendes**
Just a simple name change to get this working with RN 0.32.0

### CODE REVIEW

**Comment by chiplay** [comment]
@naoufal any chance we can land this small change and bump the version? Thanks!

**Comment by digitalcatnip** [comment]
@JBerendes I don't see how this will work - in my version of code imageURL is an NSString and loadImageWithURLRequest requires an NSURLRequest.

**Comment by JBerendes** [comment]
@digitalcatnip, I think you are correct here. What I'm getting out of it is a functional side-effect. In other words the activity view will show up where it wouldn't before this change. I'll take another crack at it.

**Comment by digitalcatnip** [comment]
@JBerendes This was the code that I used to fix it in my local project:

https://github.com/naoufal/react-native-activity-view/issues/57#issuecomment-251011947

**Comment by ryancoughlin** [comment]
Bump to get this merged in!

**Comment by mattapperson** [comment]
Bump! 

BTW, hey @ryancoughlin! Fancy seeing you here lol

**Pull request merged**
