### PR TITLE
fix: RN0.26

### PR DESCRIPTION
**Pull request by m-hosoi**

### CODE REVIEW

**Comment by Elyx0** [comment]
Tested, it does indeed fix for RN .26

**Comment by JBerendes** [comment]
I've also confirmed that this fix is working for RN0.26

**Comment by cmcewen** [comment]
This removes the anchor functionality though - is there any reason for that? I believe the only RN changes should be changing the way imports work

**Comment by BlakeWilliams** [comment]
I think this is stale since the PR I just merged fixes issues on 0.39.x for me. Closing this but if it's still a problem feel free to ping me.

**Pull request closed without merging**
